services:
  postgres:
    image: postgres:16
    container_name: cms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cmsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cms_backend
    depends_on:
      - postgres
    ports:
      - "5001:5000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: cmsdb

  frontend:
    build: ./frontend
    container_name: cms_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data: